### ISSUE TITLE
Todo list for VIPPlus plugin

### ISSUE THREAD

**Issue by ChalkPE** [if-Team/PMMP-Plugins#55]
VIP+ 플러그인

- [x] ~~1. 돈 5만 달러~~
- [x] ~~2. 게임 중 무조건 금 갑옷이 입혀짐~~
- [x] ~~3. 칭호 (채팅 및 닉네임)~~
- [x] 4. 해당 유저의 작물이 빠르게 자람
- [x] ~~5. 유저의 말이 황금색으로 나옴~~
- [x] 6. 광산에서 희귀 아이템이 드롭될 확률 상승
- [x] ~~7. 화살을 쏠 때 불화살이 나감~~
- [x] ~~8. PVP에 참가하지 않을 권리~~
- [x] ~~9. 주변을 불타게 하는 인페르노 사용 가능~~ - [`7a6b368`](https://github.com/if-Team/PMMP-Plugins/commit/7a6b368706d926a3633e4d0e66750cc17624be2f)
- [x] ~~10. 주변 유저들 힐링 가능~~ - [`7a6b368`](https://github.com/if-Team/PMMP-Plugins/commit/7a6b368706d926a3633e4d0e66750cc17624be2f)

**Comment by ChalkPE** [comment]
@HmHmmHm 이제 남은 두 기능은 흠님이 작업해 주시면 되겠습니다

**Comment by 64FF00** [comment]
@ChalkPE @HmHmmHm hm님 ㅊㅊ :tongue:

**Comment by HmHmmHm** [comment]
작업완료했습니다 완성!
