### ISSUE TITLE
To-do list for Cameraman

### ISSUE THREAD

**Issue by ChalkPE** [if-Team/PMMP-Plugins#85]
- [ ] Curve for Movement
- [ ] Compatibility for ModPE to open the screen on the clients
- [ ] Another Movement (Not A to B)
- [ ] Saving waypoints
- [ ] Translation
- [ ] Delay when startup and finished time

**Comment by ChalkPE** [comment]
Go to [New issue tracker](https://github.com/ChalkPE/Cameraman/issues/1)
